# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78e117c093aabcb547ea187a2b4e711805500bbc1d93f7ccc4057f5c9017b024d4e3be0f4c55245056d3b45e240d0c7cfa1ff69d9b0f0eed1dc3d70dc676fcf4

test:
  secret_key_base: fdb15412f5c4c2367c803313a72da93fd27fb08a152faf38954d1fd45c2fa36b774982a71df05fae7dbd8f3bfbb98359d30ab5115cc7341c1fd774b3eab0d353

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
